function PrintTable(SuperpathwayFile, ScaledEssenFile, Output)
%Writes the table generated by 'PrintPPIEssentiality.m' to disk. This table contains the 
%interaction essentiality values for each cell source/target interaction, indicates which
%interactions are "novel" (added to superpathway from screening experiments), and captures
%the sub-pathways where each interaction participates.
%inputs:
%SuperpathwayFile - filename and path of the superpathway definition generated by 
%					'GenerateSuperpathway.m'.
%ScaledEssenFile - filename and path of interaction essentialities generated by 
%					'ScaleEssentialities.m'.
%Output - desired path and filename of output tab-delimited text file.

load(SuperpathwayFile);
p_Novel  = Novel;

load(ScaledEssenFile);
Source = Essentialities.Source;
Target = Essentialities.Target ;
essen_table = Essentialities.Labels;

for i = 1:size(labels,1)
    
    for j = 1:size(labels,2)
        if(~isnan(Essentialities.Values(i,j)))
            essen_table{i}{j} = {num2str(Essentialities.Values(i,j))};
        end
            
    end
end

Pathways = cell(length(Source),1);

for i =1:length(Source)
    Pathways{i} = PathwayNames(PathwayMapping{i});
end

p = cellfun(@(x)ReLimit(x, ','), Pathways, 'UniformOutput', false);

table = PrintPPIEssentiality(essen_table, Source, Target,...
                                   p_Novel, p, Lines, Histology );
result = cell2text(table, Output);



